### PR TITLE
fix: CI release failed

### LINKED ISSUE #15: [Bug] Release CI failed
image

### PR DESCRIPTION
**Pull request by ffyuanda**
Fix: #15 

Signed-off-by: ffyuanda <46557895+ffyuanda@users.noreply.github.com>

### CODE REVIEW

**Comment by ffyuanda** [comment]
Here is the successful test instance: https://pypi.org/project/casbin-postgresql-watcher-test/

**Comment by ffyuanda** [comment]
@techoner @Zxilly plz review

**Comment by Zxilly** [comment]
@ffyuanda if you want to test publish, you should use test_pypi, but not the pypi.

**Comment by Zxilly** [comment]
And why this commit exist https://github.com/pycasbin/postgresql-watcher/pull/16/commits/45a12fbde9db6ab2064c40d78af2bb55c7b607c5

**Comment by ffyuanda** [comment]
@Zxilly yeah I should've done that, but I was lazy and the semantic-release-pypi plugin is default to publish on pypi instead of test_pypi, I will delete the test publish later.

**Comment by ffyuanda** [comment]
> And why this commit exist [45a12fb](https://github.com/pycasbin/postgresql-watcher/commit/45a12fbde9db6ab2064c40d78af2bb55c7b607c5)

@Zxilly I'm also trying to figure out why it is there

**Comment by ffyuanda** [comment]
@Zxilly it should be gone now

**Review by Zxilly — APPROVED** [review]
lgtm

**Pull request merged**
