### PR TITLE
feat: add database name parameter to watcher.

### PR DESCRIPTION
**Pull request by Tyskiep99**
Add a `dbname` parameter for the `connect` function to psql.
Remove unused imports

### CODE REVIEW

**Comment by Tyskiep99** [comment]
cherry picked 2e3c5e727442db0e1b41a689139bcdc225468dd5 from https://github.com/pycasbin/postgresql-watcher/pull/18

**Comment by hsluoyz** [comment]
@Tyskiep99 plz rebase this PR

**Comment by hsluoyz** [comment]
@leeqvip

**Review by Zxilly — APPROVED** [review]
lgtm

**Comment by Zxilly** [comment]
@Tyskiep99 plz also update readme

**Pull request merged**
