### PR TITLE
Deleted macOS Action tests and outdated Python 3.5 Action tests

### PR DESCRIPTION
**Pull request by ffyuanda**
macOS is not currently under the support of Docker container "service", only Linux environments can implement the Setup Postgresql step. Relative test actions might need to be manually written using JavaScript actions without running in a container, but directly on the Github runner machine.

Python 3.5 is no longer supported, and pip does not work well under Python 3.5 right now.

### CODE REVIEW

**Comment by ffyuanda** [comment]
relative info regarding Actions:
[(https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions)](url)

**Comment by hsluoyz** [comment]
@ffyuanda plz fix:

image

**Comment by ffyuanda** [comment]
@hsluoyz will do

**Review by Zxilly — APPROVED** [review]
please fix failed check

**Pull request closed without merging**
